int isalpha(int c) __attribute__((const));
int isdigit(int c) __attribute__((const));
int islower(int c) __attribute__((const));
int isprint(int c) __attribute__((const));
int isspace(int c) __attribute__((const));
int isupper(int c) __attribute__((const));
int isxdigit(int c) __attribute__((const));
int tolower(int c) __attribute__((const));
int toupper(int c) __attribute__((const));
